FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
CMD ["celery", "-A", "app.development_checkpoints.infrastructure.queue.celery_app", "worker", "-Q", "gpu", "--loglevel=INFO", "--concurrency=1"]
