FROM python:3.11-slim
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
CMD ["celery", "-A", "app.development_checkpoints.infrastructure.queue.celery_app", "worker", "-Q", "cpu", "--loglevel=INFO"]
