FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1
COPY ./requirements.txt /code/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade -r /code/requirements.txt
COPY ./app /code/app
CMD ["celery", "-A", "app.development_checkpoints.infrastructure.queue.celery_app", "worker", "-Q", "gpu", "--loglevel=INFO", "--concurrency=1"]
