/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedProfessionalRouteImport } from './routes/_authenticated/professional'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLayananRouteImport } from './routes/_authenticated/layanan'
import { Route as AuthenticatedJurnalRouteImport } from './routes/_authenticated/jurnal'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBerandaRouteImport } from './routes/_authenticated/beranda'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAsistenRouteImport } from './routes/_authenticated/asisten'
import { Route as AuthenticatedAidRouteImport } from './routes/_authenticated/aid'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people.$personId'
import { Route as AuthenticatedJournalTrendRouteImport } from './routes/_authenticated/journal.trend'
import { Route as AuthenticatedJournalModeNewRouteImport } from './routes/_authenticated/journal.$mode.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessionalRoute =
  AuthenticatedProfessionalRouteImport.update({
    id: '/professional',
    path: '/professional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLayananRoute = AuthenticatedLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurnalRoute = AuthenticatedJurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerandaRoute = AuthenticatedBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenRoute = AuthenticatedAsistenRouteImport.update({
  id: '/asisten',
  path: '/asisten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAidRoute = AuthenticatedAidRouteImport.update({
  id: '/aid',
  path: '/aid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedJournalTrendRoute =
  AuthenticatedJournalTrendRouteImport.update({
    id: '/trend',
    path: '/trend',
    getParentRoute: () => AuthenticatedJournalRoute,
  } as any)
const AuthenticatedJournalModeNewRoute =
  AuthenticatedJournalModeNewRouteImport.update({
    id: '/$mode/new',
    path: '/$mode/new',
    getParentRoute: () => AuthenticatedJournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aid': typeof AuthenticatedAidRoute
  '/asisten': typeof AuthenticatedAsistenRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRouteWithChildren
  '/jurnal': typeof AuthenticatedJurnalRoute
  '/layanan': typeof AuthenticatedLayananRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/professional': typeof AuthenticatedProfessionalRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/services': typeof AuthenticatedServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/journal/trend': typeof AuthenticatedJournalTrendRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/journal/$mode/new': typeof AuthenticatedJournalModeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aid': typeof AuthenticatedAidRoute
  '/asisten': typeof AuthenticatedAsistenRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRouteWithChildren
  '/jurnal': typeof AuthenticatedJurnalRoute
  '/layanan': typeof AuthenticatedLayananRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/professional': typeof AuthenticatedProfessionalRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/services': typeof AuthenticatedServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/journal/trend': typeof AuthenticatedJournalTrendRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/journal/$mode/new': typeof AuthenticatedJournalModeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aid': typeof AuthenticatedAidRoute
  '/_authenticated/asisten': typeof AuthenticatedAsistenRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/beranda': typeof AuthenticatedBerandaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRouteWithChildren
  '/_authenticated/jurnal': typeof AuthenticatedJurnalRoute
  '/_authenticated/layanan': typeof AuthenticatedLayananRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/professional': typeof AuthenticatedProfessionalRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/journal/trend': typeof AuthenticatedJournalTrendRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/journal/$mode/new': typeof AuthenticatedJournalModeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/aid'
    | '/asisten'
    | '/assistant'
    | '/beranda'
    | '/dashboard'
    | '/journal'
    | '/jurnal'
    | '/layanan'
    | '/onboarding'
    | '/pengaturan'
    | '/people'
    | '/professional'
    | '/roadmap'
    | '/services'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/journal/trend'
    | '/people/$personId'
    | '/journal/$mode/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/aid'
    | '/asisten'
    | '/assistant'
    | '/beranda'
    | '/dashboard'
    | '/journal'
    | '/jurnal'
    | '/layanan'
    | '/onboarding'
    | '/pengaturan'
    | '/people'
    | '/professional'
    | '/roadmap'
    | '/services'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/journal/trend'
    | '/people/$personId'
    | '/journal/$mode/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/aid'
    | '/_authenticated/asisten'
    | '/_authenticated/assistant'
    | '/_authenticated/beranda'
    | '/_authenticated/dashboard'
    | '/_authenticated/journal'
    | '/_authenticated/jurnal'
    | '/_authenticated/layanan'
    | '/_authenticated/onboarding'
    | '/_authenticated/pengaturan'
    | '/_authenticated/people'
    | '/_authenticated/professional'
    | '/_authenticated/roadmap'
    | '/_authenticated/services'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/journal/trend'
    | '/_authenticated/people/$personId'
    | '/_authenticated/journal/$mode/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional': {
      id: '/_authenticated/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof AuthenticatedProfessionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/layanan': {
      id: '/_authenticated/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof AuthenticatedLayananRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurnal': {
      id: '/_authenticated/jurnal'
      path: '/jurnal'
      fullPath: '/jurnal'
      preLoaderRoute: typeof AuthenticatedJurnalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beranda': {
      id: '/_authenticated/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AuthenticatedBerandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asisten': {
      id: '/_authenticated/asisten'
      path: '/asisten'
      fullPath: '/asisten'
      preLoaderRoute: typeof AuthenticatedAsistenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aid': {
      id: '/_authenticated/aid'
      path: '/aid'
      fullPath: '/aid'
      preLoaderRoute: typeof AuthenticatedAidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/journal/trend': {
      id: '/_authenticated/journal/trend'
      path: '/trend'
      fullPath: '/journal/trend'
      preLoaderRoute: typeof AuthenticatedJournalTrendRouteImport
      parentRoute: typeof AuthenticatedJournalRoute
    }
    '/_authenticated/journal/$mode/new': {
      id: '/_authenticated/journal/$mode/new'
      path: '/$mode/new'
      fullPath: '/journal/$mode/new'
      preLoaderRoute: typeof AuthenticatedJournalModeNewRouteImport
      parentRoute: typeof AuthenticatedJournalRoute
    }
  }
}

interface AuthenticatedJournalRouteChildren {
  AuthenticatedJournalTrendRoute: typeof AuthenticatedJournalTrendRoute
  AuthenticatedJournalModeNewRoute: typeof AuthenticatedJournalModeNewRoute
}

const AuthenticatedJournalRouteChildren: AuthenticatedJournalRouteChildren = {
  AuthenticatedJournalTrendRoute: AuthenticatedJournalTrendRoute,
  AuthenticatedJournalModeNewRoute: AuthenticatedJournalModeNewRoute,
}

const AuthenticatedJournalRouteWithChildren =
  AuthenticatedJournalRoute._addFileChildren(AuthenticatedJournalRouteChildren)

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAidRoute: typeof AuthenticatedAidRoute
  AuthenticatedAsistenRoute: typeof AuthenticatedAsistenRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBerandaRoute: typeof AuthenticatedBerandaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRouteWithChildren
  AuthenticatedJurnalRoute: typeof AuthenticatedJurnalRoute
  AuthenticatedLayananRoute: typeof AuthenticatedLayananRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedProfessionalRoute: typeof AuthenticatedProfessionalRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAidRoute: AuthenticatedAidRoute,
  AuthenticatedAsistenRoute: AuthenticatedAsistenRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBerandaRoute: AuthenticatedBerandaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRouteWithChildren,
  AuthenticatedJurnalRoute: AuthenticatedJurnalRoute,
  AuthenticatedLayananRoute: AuthenticatedLayananRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedProfessionalRoute: AuthenticatedProfessionalRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
